### ISSUE TITLE
Fix dc/os base url handling

### ISSUE THREAD

**Issue by adersberger** [qaware/kubepad#12]
right now ow "/" is inserted between the marathon url endpoint and the service path. There are dcos.tomls where no "/" is at the end so the service calls will fail. Implement logic in MethodProducer (line 58) to insert a "/" if required.

**Comment by voidc** [comment]
Fixed in https://github.com/qaware/kubepad/commit/547a1501fbf0886c94fe034127ed9c62228dfe94
