### ISSUE TITLE
Fix master URL only taken from properties instead of .kube/config

### ISSUE THREAD

**Issue by lreimer** [qaware/kubepad#20]
Only the hardcoded master URL in the properties is honored. If not set we want to use the .kube/config setting again. No reproduction steps.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue description must include reproduction steps [(?)](https://gitmagic.io/rules/#/issue/body-must-include-reproduction-steps)
- Issue title must be in imperative, present tense (e.g. "add", "fix", "change") [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/qaware/kubepad/20/1466b55d-817a-4e7d-85af-cae0cb2d751d/2ba986a9-f369-4e73-8d9b-37315539e64a) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue description must include reproduction steps [(?)](https://gitmagic.io/rules/#/issue/body-must-include-reproduction-steps)
- Issue title must be in imperative, present tense (e.g. "add", "fix", "change") [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/qaware/kubepad/20/1466b55d-817a-4e7d-85af-cae0cb2d751d/2ba986a9-f369-4e73-8d9b-37315539e64a) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:
- Issue title must be in imperative, present tense (e.g. "add", "fix", "change") [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/qaware/kubepad/20/1466b55d-817a-4e7d-85af-cae0cb2d751d/2ba986a9-f369-4e73-8d9b-37315539e64a) for details.

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
