### ISSUE TITLE
Will this work against MkII Mini LaunchPad?

### ISSUE THREAD

**Issue by cris-pin** [qaware/kubepad#21]
Hi, Will this work against the MKII Mini LaunchPad that Novation offer?

Many thanks

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
- Issue title must be in imperative, present tense (e.g. "add", "fix", "change") [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/qaware/kubepad/21/1466b55d-817a-4e7d-85af-cae0cb2d751d/2e6fcced-974b-4200-87b6-04433161faf8) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:
- Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/qaware/kubepad/21/1466b55d-817a-4e7d-85af-cae0cb2d751d/2e6fcced-974b-4200-87b6-04433161faf8) for details.

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by lreimer** [comment]
Not sure. But my guess is no. I can only find a Programmer's Reference Manual for the Launchpad MK2.
Maybe some of the MIDI commands are the same, but since the button layout is different chances are pretty high that it will not work 100%.

**Comment by lreimer** [comment]
Maybe you can ask Novation if the MKII Mini LaunchPad can be programmed exactly like its bigger brother.

**Comment by ghost** [comment]
This issue still violates some of our guidelines:
- Issue title must be in imperative, present tense (e.g. "add", "fix", "change") [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/qaware/kubepad/21/1466b55d-817a-4e7d-85af-cae0cb2d751d/2e6fcced-974b-4200-87b6-04433161faf8) for details.

**Comment by cris-pin** [comment]
Thank-you very much
