### ISSUE TITLE
Implement OpenShift support

### ISSUE THREAD

**Issue by lreimer** [qaware/kubepad#22]
Add OpenShift logic to use DeploymentConfigs instead of Kubernetes Deployments.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must not end with a dot [(?)](https://gitmagic.io/rules/#/issue/subject-must-not-end-with-dot)

[Click here](https://app.gitmagic.io/qaware/kubepad/22/1466b55d-817a-4e7d-85af-cae0cb2d751d/d37ae14c-611c-4c60-935d-a189a9930a28) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must not end with a dot [(?)](https://gitmagic.io/rules/#/issue/subject-must-not-end-with-dot)

[Click here](https://app.gitmagic.io/qaware/kubepad/22/1466b55d-817a-4e7d-85af-cae0cb2d751d/d37ae14c-611c-4c60-935d-a189a9930a28) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by lreimer** [comment]
Fixed in v1.3.0.
