### ISSUE TITLE
Implement REST Client for Marathon API

### ISSUE THREAD

**Issue by lreimer** [qaware/kubepad#5]
Use Retrofit (or any other service client library) to implement a REST Client for the Marathon API.
Write tests using WireMock.

**Comment by lreimer** [comment]
Alternatively try marathon-client project from GirtHub.

**Comment by adersberger** [comment]
See exercise from Cloud Computing lecture on how to use the Marathon API from Java: https://github.com/adersberger/cloudcomputing/tree/master/06-cluster-scheduling/uebung.
The solution also supports token-based auth and uses as simple REST client lib.

Here is an example on how to use either Feign or Retrofit to call REST services (from Java8 as well as Kotlin): https://github.com/adersberger/restclients
